from decimal import Decimal

SOURCE_URL = "https://taostats.io/subnets"
RAO_PER_UNIT = Decimal("1000000000")

AN = 2
STAKING_HOTKEY = "5F1xUaixHnpfyqUj77YHEDPNssYkyZwd2T7wdGCVtJ8U7a9o"
STOCKS_HOTKEY = "5Ccq57P5jtBKzgKDRPkxMViJrJSDyCWDcqkkpbxsKDMJbJcP"
STAKING_UID = 85
STOCKS_UID = 246

BASE_BLOCK = 7718400
BASE_TIME_STR = '2026-03-11 01:00:00'
BLOCK_SECONDS = 12

STAKING_STRATEGY_PATH = 'Investing/strat/{}'.format(STAKING_HOTKEY)
STAKING_STRATEGY_PATH_CSV = 'Investing/strat/{}.csv'.format(STAKING_HOTKEY)
STOCKS_STRATEGY_PATH = 'Investing/strat/{}'.format(STOCKS_HOTKEY)
STOCKS_STRATEGY_PATH_CSV = 'Investing/strat/{}.csv'.format(STOCKS_HOTKEY)
DATA_NAME = "data.csv"

STAKING_FUND = 1000
STOCKS_FUND = 10000000

ASSET = 1
